### ISSUE TITLE
Proposal for zproject_class.gsl reorganisation and simplification

### ISSUE THREAD

**Issue by dmeehan1968** [zeromq/zproject#156] opened 2015-02-22 23:40 UTC
I've been looking at zproject_class.gsl implementation, and would like to propose the following changes.  Please comment if there is good reason to maintain any aspect of the current implementation.

- Remove the initial generation and regeneration of the class header.  The file only contains generated output, and not user edits that need preserving, so this seems to be a hangover from earlier.
- Make constructor, destructor, print and test methods defaults in the 'method' collection if not specified in the api model.  Use these for generation in the header and initial source module, as opposed to canned.  This allows for more flexibility in arguments.
- Rename zproject_class.gsl to zproject_binding_c.gsl for consistency with other bindings
- Rename zproject_class_api.gsl to zproject_utils_c.gsl for clarity. Other bindings could follow if desired for consistency and improved modularity.
- Allow for 'delete' option on constructor, destructor, print and test methods to suppress output.  I have a use case where the constructor is not required.

**Comment by hintjens** [comment] 2015-02-23 07:58
In general make one change per problem you can identify, don't break
existing apps, and we'll merge.

Regarding the class types (constructor, print, test, etc.) perhaps we need
some abstraction here. E.g. three types of class, one with only test, one
also with constructor/destructor and one with _dup and _print as well.

**Comment by twhittock** [comment] 2015-02-23 08:39
hi @dmeehan1968 - I've been working on this stuff quite a lot recently, so I thought I'd let you know my thoughts.

* removing initial generation/regeneration - i thought this at first too, but actually stuff outside the @interface/@end block can and will be hand edited - CZMQ does this quite a lot, especially with zsock, but other classes too.
* make ctor/dtor/print/test default - this is done in #157 
* rename zproject_class to bindings_c - makes sense given the number of other bindings, i think, though zproject is very much a C oriented project - not sure it's really a 'binding' as much as the whole point of the thing :) this becomes more clear when we think about the nature of the other bindings - they are all non-idiomatic, due to them really just being a copy of the 
* rename zproject_class_api - this does a combination of initial model resolution (adding defaults, checking arguments etc) with some c bindings stuff. it's not really just c utilities - everything relies on this being run. i'd like to see some of the c bindings stuff get extracted out, but some other bindings rely on that (ruby)
* 'delete' option - In #157 I used a class-level attribute 'has_print', but i much prefer your idea - add a new node in the class `<delete method="print" />` and (not sure about how to spell this exactly) `<delete constructor="" />` or `<delete_constructor />`

**Comment by dmeehan1968** [comment] 2015-02-23 08:54
@twhittock thanks for the reply.

- regarding regeneration, can we remove the stubbed dtor, ctor, print and test methods from initial header generation, and modify class_api.gsl to add them as methods if missing?
- regarding deletion, is was thinking of `<constructor delete = "1" />`, so a delete attribute, not node.  Same for others.

Will probably hold off on the others for now, till I get better understanding of the other bindings dependencies.

**Comment by twhittock** [comment] 2015-02-23 09:20
the interface regeneration only occurs if you have an api file defined for that class - so the initial path to entry (edit project.xml, add a class node with a name) won't be as easy - you'd also have to add an api/class.xml file too - many existing projects don't use that functionality at all.

If we automatically created default api nodes for classes with missing api/class.xml files, then we'd have to check the rest of the zproject gsl files - there are various places where we check if an api node was defined, and if so we treat it specially. That logic would have to change everywhere. Ultimately that would just create extra work, without much gain that I can see. Depends on what your goal is, really.

Deletion attribute makes sense to me - probably cleaner - less surface area to document etc. If you do it, please delete the has_print stuff from czmq, too - I wasn't too happy with that, but it was the simplest thing I could think of.

**Comment by dmeehan1968** [comment] 2015-02-23 09:48
@twhittock ok, I think I'd got the wrong end of the stick.

The docs could probably do with improving, but here is my understanding.

- if you add a <class> node to project.xml, you get a boilerplate header with constructor, destructor, print and test methods.
- if you add an api/{class}.xml file with the same name as the class node, you get default constructor and destructor, any overrides from the api description.  You loose print and test, unless you define them yourself in the api description.

If that's the intended behaviour (or what people now expect) then my previous edits to regenerate print and test are probably incorrect, although the subsequent edit probably resolves the conflicts, it means that test and print are now mandatory for api defined classes, not optional (which I think is what the CLASS spec says they should be).

As a result, those edits should probably be reverted, and I can add them back to my project myself.

**Comment by twhittock** [comment] 2015-02-23 10:07
Yep that's pretty much my understanding too - I'm not sure about the CLASS spec or intended behaviour - I just added the features needed to get the classes I wanted available in Python - the overall design isn't something I've focussed on. I think CLASS having a spec for print, dup, test etc makes sense - bindings can use higher level information to become closer to being idiomatic.

**Comment by jemc** [comment] 2015-02-23 17:50
A lot of the issues brought up here are indeed due to the fact that the generated bindings were something I tacked on as an additional feature of zproject not in the original scope.  I'm glad to see others are interested in using them and making them better.

In my opinion, we should do what we can to provide a clean, consistent experience for zproject even if it means small breaks in existing zprojects, as long as we can make upgrading easy whether it's a short guide of changes and fixes to the design published here, or adding deprecation warnings to the generator scripts, or something else.  It seems like zproject is not that widely adopted yet, and the bindings feature is definitely not that widely adopted, with most of the stakeholders already involved here in this conversation and tracking changes on github.  So it seems to me the time to clean up the experience is now, before adoption increases.  Having a cleaner experience also means more potential users will end up adopting zproject.

As a small side note, @twhittock, you've done awesome work on the python bindings and the CZMQ migration - I'm so grateful for you sharing your talents with us and I'm excited to take an audit this week of what new features and applications I can support in my projects thanks to your work.

Let's continue making zproject the most powerful way to build language-portable C libraries!

**Comment by hintjens** [comment] 2015-02-23 18:16
+1 on improving things now; zproject is what I'd consider "draft".

My main concern would be to keep a clean abstraction level so the model
language stays high above whatever build systems we're using. Don't be
afraid to explore concepts that package up complexity...

-Pieter

**Comment by dmeehan1968** [comment] 2015-02-23 23:48
as I tihink I'd proposed originaly, it seems zproject needs some significant reorganisation if it's going to support multiple language bindings.  If existing projects are already dependent on its current behaviour, then it probably needs a separate branch so there is some scope to break things in the short term.

**Comment by jemc** [comment] 2015-02-24 00:07
@dmeehan1968 
Here are my opinions so far on the points in your original post:
>Remove the initial generation and regeneration of the class header. The file only contains generated output, and not user edits that need preserving, so this seems to be a hangover from earlier.

This would make things simpler, but breaks (at least) CZMQ in a pretty big way.  If you figure out a good way to solve the CZMQ problem, I'm okay with this

> Make constructor, destructor, print and test methods defaults in the 'method' collection if not specified in the api model. Use these for generation in the header and initial source module, as opposed to canned. This allows for more flexibility in arguments.

I think the first part of this is already done by @twhittock.  I wholeheartedly agree with the second part.

> Rename zproject_class.gsl to zproject_binding_c.gsl for consistency with other bindings

As mentioned by others above, I don't really consider the C code to be a binding, but the thing being bound to. 

Rename zproject_class_api.gsl to zproject_utils_c.gsl for clarity. Other bindings could follow if desired for consistency and improved modularity.

We could consider shifting elements of these around, but noting my point above that the C header is not a binding, but the thing being bound to, we are dealing with two fundamanetal translations of the source model here:

1. The abstract model => the C method signatures
2. The C method signatures => the bindings for any given language

I think it is important for DRYness that the logic in point 1 not be duplicated by each binding, which is why I think it important that that transformation exist in a shared stage.  So I'm not in favor of making this stage a C-only stage.

> Allow for 'delete' option on constructor, destructor, print and test methods to suppress output. I have a use case where the constructor is not required.

Sounds good to me. :+1:

**Comment by jemc** [comment] 2015-03-01 19:33
The 'delete' option for methods discussed here has been implemented as support for an `exclude = "1"` attribute in https://github.com/zeromq/zproject/pull/166.
The name `exclude` was chosen because of possible confusion `delete = "1"` might cause when seen in constructors or destructors (with regard to memory freeing/deletion).

**Comment by jemc** [comment] 2015-03-01 19:36
Much of this ticket has been resolved, but because it combines many separate problems, marking it as resolved is not entirely true.

I'm going to go ahead and close this ticket.  If concerns persist, let's deal with them in one issue ticket per problem, as @hintjens suggested.

**Closed by jemc** 2015-03-01 19:36 UTC
